# Git Hook Setup Script for Branch-Specific File Isolation
param(
    [switch]$Force
)

$devOnlyFiles = Get-Content .repo-config/dev-only-files.txt | Where-Object { $_ -notmatch '^\s*#' -and $_ -match '\S' }

Write-Host "`nFiles to isolate (dev only):" -ForegroundColor Cyan
$devOnlyFiles | ForEach-Object { Write-Host "  - $_" -ForegroundColor White }

$hookPath = ".git/hooks/post-merge"
if ((Test-Path $hookPath) -and -not $Force) {
    $response = Read-Host "`npost-merge hook already exists. Overwrite? (y/N)"
    if ($response -notmatch '^y(es)?$') {
        Write-Host "Aborted. Use -Force to overwrite without prompting." -ForegroundColor Yellow
        exit 0
    }
}

$hookContent = @"
#!/bin/sh
# Post-merge hook - maintains branch-specific file isolation
# Generated by .repo-config/setup-hooks.ps1

CURRENT_BRANCH=`$(git branch --show-current)
DEV_ONLY_FILES="$($devOnlyFiles -join ' ')"

if [ "`$CURRENT_BRANCH" = "main" ]; then
    # Main: Delete dev-only files from disk and ensure .gitignore blocks them
    for file in `$DEV_ONLY_FILES; do
        if [ -f "`$file" ]; then
            echo "Removing dev-only file from main: `$file"
            rm -f "`$file"
        fi
    done
    
    # Update .gitignore to ignore dev-only files on main
    echo "# Main branch - excludes dev-only documentation files" > .gitignore
    for file in `$DEV_ONLY_FILES; do
        echo "`$file" >> .gitignore
    done
    
    # Stage .gitignore changes
    git add .gitignore
    
    # Auto-commit if there are changes
    if ! git diff --cached --quiet 2>/dev/null; then
        git commit --no-edit --no-verify -m "Auto-update .gitignore for main branch"
    fi
    
elif [ "`$CURRENT_BRANCH" = "dev" ]; then
    # Dev: Restore dev-only files if deleted by merge
    for file in `$DEV_ONLY_FILES; do
        if ! git ls-files --error-unmatch "`$file" > /dev/null 2>&1; then
            # Try to find the file in recent dev branch history
            LAST_COMMIT=`$(git log --all --format=%H --diff-filter=D -- "`$file" | head -1)
            if [ -n "`$LAST_COMMIT" ]; then
                PARENT_COMMIT=`$(git rev-parse `$LAST_COMMIT^)
                if git show `$PARENT_COMMIT:"`$file" > /dev/null 2>&1; then
                    echo "Restoring dev-only file: `$file"
                    mkdir -p "`$(dirname "`$file")"
                    git show `$PARENT_COMMIT:"`$file" > "`$file"
                    git add "`$file"
                fi
            fi
        fi
    done
    
    # Update .gitignore to allow dev-only files on dev
    echo "# Dev branch - includes documentation files" > .gitignore
    
    # Stage .gitignore changes
    git add .gitignore
    
    # Auto-commit restored files and .gitignore
    if ! git diff --cached --quiet 2>/dev/null; then
        git commit --no-edit --no-verify -m "Auto-restore dev-only files and update .gitignore"
    fi
fi
"@

# Ensure hooks directory exists
New-Item -ItemType Directory -Path .git/hooks -Force | Out-Null

# Write hook script
$hookContent | Out-File -FilePath $hookPath -Encoding ASCII -NoNewline

# Make executable (Windows git bash will handle this)
git update-index --chmod=+x $hookPath

Write-Host "`n✓ post-merge hook installed successfully!" -ForegroundColor Green
Write-Host "`nThe hook will automatically:" -ForegroundColor Cyan
Write-Host "  - Remove dev-only files from main after merges" -ForegroundColor White
Write-Host "  - Restore dev-only files to dev after merges" -ForegroundColor White